config/routes.rb
Rails.application.routes.draw do
  resources :high_scores
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/high_score.rb
class HighScore < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/high_scores_controller.rb
class HighScoresController < ApplicationController
  before_action :set_high_score, only: [:show, :edit, :update, :destroy]

  # GET /high_scores
  # GET /high_scores.json
  def index
    @high_scores = HighScore.all
  end

  # GET /high_scores/1
  # GET /high_scores/1.json
  def show
  end

  # GET /high_scores/new
  def new
    @high_score = HighScore.new
  end

  # GET /high_scores/1/edit
  def edit
  end

  # POST /high_scores
  # POST /high_scores.json
  def create
    @high_score = HighScore.new(high_score_params)

    respond_to do |format|
      if @high_score.save
        format.html { redirect_to @high_score, notice: 'High score was successfully created.' }
        format.json { render :show, status: :created, location: @high_score }
      else
        format.html { render :new }
        format.json { render json: @high_score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /high_scores/1
  # PATCH/PUT /high_scores/1.json
  def update
    respond_to do |format|
      if @high_score.update(high_score_params)
        format.html { redirect_to @high_score, notice: 'High score was successfully updated.' }
        format.json { render :show, status: :ok, location: @high_score }
      else
        format.html { render :edit }
        format.json { render json: @high_score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /high_scores/1
  # DELETE /high_scores/1.json
  def destroy
    @high_score.destroy
    respond_to do |format|
      format.html { redirect_to high_scores_url, notice: 'High score was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_high_score
      @high_score = HighScore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def high_score_params
      params.require(:high_score).permit(:game, :score)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def javascript(*files)
    content_for(:head) { javascript_include_tag(*files) }
  end
end

app/helpers/high_scores_helper.rb
module HighScoresHelper
end

app/views/high_scores/_form.html.erb
<%= form_for(high_score) do |f| %>
  <% if high_score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(high_score.errors.count, "error") %> prohibited this high_score from being saved:</h2>

      <ul>
      <% high_score.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :game %>
    <%= f.text_field :game %>
  </div>

  <div class="field">
    <%= f.label :score %>
    <%= f.number_field :score %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/high_scores/_table.html.erb
<table id='score_table'>
  <thead>
    <tr>
      <th>Game</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @high_scores.each do |high_score| %>
      <tr>
        <td><%= high_score.game %></td>
        <td><%= high_score.score %></td>
        <td><%= link_to 'Show', high_score %></td>
        <td><%= link_to 'Edit', edit_high_score_path(high_score) %></td>
        <td><%= link_to 'Destroy', high_score, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/high_scores/edit.html.erb
<h1>Editing High Score</h1>

<%= render 'form', high_score: @high_score %>

<%= link_to 'Show', @high_score %> |
<%= link_to 'Back', high_scores_path %>

app/views/high_scores/index.html.erb
<% javascript 'high_scores' %>

<p id="notice"><%= notice %></p>

<h1>High Scores</h1>

<%= render 'table', high_scores: @high_scores %>

<br>

<%= link_to 'New High Score', new_high_score_path %>

app/views/high_scores/new.html.erb
<h1>New High Score</h1>

<%= render 'form', high_score: @high_score %>

<%= link_to 'Back', high_scores_path %>

app/views/high_scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Game:</strong>
  <%= @high_score.game %>
</p>

<p>
  <strong>Score:</strong>
  <%= @high_score.score %>
</p>

<%= link_to 'Edit', edit_high_score_path(@high_score) %> |
<%= link_to 'Back', high_scores_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield(:head) %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>